name: deployNodeProject
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mydatabase:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: node_db
        ports:
          - 3306:3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # - name: Prepare environment
      #   run: |
      #     if [ ! -f .env ]; then cp .env.example .env; fi
      #     npm run generate-env-key

      # - name: Run migrations
      #   run: npm run migrate

      # - name: Build application
      #   run: npm run build

      - name: Run tests
        run: npm start
